# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62759854fc3f0293b8e1f067ff62afac91c66752ae45be2e8b9e392f8e3e6d8f26add854f0b2a40ce83f3007e630634ccc03ba52fc9864300427a9440182cd8e

test:
  secret_key_base: 380659b48a70ba5df993f8d97f99a03b9213cbff58e7c7559e249f7efb67b4aad65899378fe80abc69c56d198add09fec97f95d063ee143f28a484a428bd9fa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
